var SUCCESS=200
var CREATED = 201
var NOT_FOUND=404
var FORBIDDEN =403
var INTERNAL_ERROR=500
var BAD_REQUEST = 400
var UNOTHORIZED = 401
var CONFLICT = 409

exports.code ={SUCCESS,CREATED,NOT_FOUND,FORBIDDEN,INTERNAL_ERROR,BAD_REQUEST,UNOTHORIZED,CONFLICT}

